tunnel: 5a894518-56e6-4784-84a7-3f9025bac047
credentials-file: /home/progenics-bioinfo/.cloudflared/5a894518-56e6-4784-84a7-3f9025bac047.json

ingress:
  - hostname: lims.progenicslabs.com
    service: http://localhost:4000
  - service: http_status:404
